# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mao/dpdk/DPDK-dev-demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mao/dpdk/DPDK-dev-demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mao/dpdk/DPDK-dev-demo/CMakeFiles /home/mao/dpdk/DPDK-dev-demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mao/dpdk/DPDK-dev-demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DPDK_dev_demo

# Build rule for target.
DPDK_dev_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DPDK_dev_demo
.PHONY : DPDK_dev_demo

# fast build rule for target.
DPDK_dev_demo/fast:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/build
.PHONY : DPDK_dev_demo/fast

Demo/IpSrTunnel/MaoIpRouteTableLPM.o: Demo/IpSrTunnel/MaoIpRouteTableLPM.c.o

.PHONY : Demo/IpSrTunnel/MaoIpRouteTableLPM.o

# target to build an object file
Demo/IpSrTunnel/MaoIpRouteTableLPM.c.o:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/IpSrTunnel/MaoIpRouteTableLPM.c.o
.PHONY : Demo/IpSrTunnel/MaoIpRouteTableLPM.c.o

Demo/IpSrTunnel/MaoIpRouteTableLPM.i: Demo/IpSrTunnel/MaoIpRouteTableLPM.c.i

.PHONY : Demo/IpSrTunnel/MaoIpRouteTableLPM.i

# target to preprocess a source file
Demo/IpSrTunnel/MaoIpRouteTableLPM.c.i:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/IpSrTunnel/MaoIpRouteTableLPM.c.i
.PHONY : Demo/IpSrTunnel/MaoIpRouteTableLPM.c.i

Demo/IpSrTunnel/MaoIpRouteTableLPM.s: Demo/IpSrTunnel/MaoIpRouteTableLPM.c.s

.PHONY : Demo/IpSrTunnel/MaoIpRouteTableLPM.s

# target to generate assembly for a file
Demo/IpSrTunnel/MaoIpRouteTableLPM.c.s:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/IpSrTunnel/MaoIpRouteTableLPM.c.s
.PHONY : Demo/IpSrTunnel/MaoIpRouteTableLPM.c.s

Demo/SegmentRouting/mplsForwardTable.o: Demo/SegmentRouting/mplsForwardTable.c.o

.PHONY : Demo/SegmentRouting/mplsForwardTable.o

# target to build an object file
Demo/SegmentRouting/mplsForwardTable.c.o:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/SegmentRouting/mplsForwardTable.c.o
.PHONY : Demo/SegmentRouting/mplsForwardTable.c.o

Demo/SegmentRouting/mplsForwardTable.i: Demo/SegmentRouting/mplsForwardTable.c.i

.PHONY : Demo/SegmentRouting/mplsForwardTable.i

# target to preprocess a source file
Demo/SegmentRouting/mplsForwardTable.c.i:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/SegmentRouting/mplsForwardTable.c.i
.PHONY : Demo/SegmentRouting/mplsForwardTable.c.i

Demo/SegmentRouting/mplsForwardTable.s: Demo/SegmentRouting/mplsForwardTable.c.s

.PHONY : Demo/SegmentRouting/mplsForwardTable.s

# target to generate assembly for a file
Demo/SegmentRouting/mplsForwardTable.c.s:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/SegmentRouting/mplsForwardTable.c.s
.PHONY : Demo/SegmentRouting/mplsForwardTable.c.s

Demo/main.o: Demo/main.c.o

.PHONY : Demo/main.o

# target to build an object file
Demo/main.c.o:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/main.c.o
.PHONY : Demo/main.c.o

Demo/main.i: Demo/main.c.i

.PHONY : Demo/main.i

# target to preprocess a source file
Demo/main.c.i:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/main.c.i
.PHONY : Demo/main.c.i

Demo/main.s: Demo/main.c.s

.PHONY : Demo/main.s

# target to generate assembly for a file
Demo/main.c.s:
	$(MAKE) -f CMakeFiles/DPDK_dev_demo.dir/build.make CMakeFiles/DPDK_dev_demo.dir/Demo/main.c.s
.PHONY : Demo/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DPDK_dev_demo"
	@echo "... Demo/IpSrTunnel/MaoIpRouteTableLPM.o"
	@echo "... Demo/IpSrTunnel/MaoIpRouteTableLPM.i"
	@echo "... Demo/IpSrTunnel/MaoIpRouteTableLPM.s"
	@echo "... Demo/SegmentRouting/mplsForwardTable.o"
	@echo "... Demo/SegmentRouting/mplsForwardTable.i"
	@echo "... Demo/SegmentRouting/mplsForwardTable.s"
	@echo "... Demo/main.o"
	@echo "... Demo/main.i"
	@echo "... Demo/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

